app_post_create:
  path: /post
  methods: ["POST"]
  defaults: { _controller: App\Controller\PostController::create }

app_post_index:
  path: /post
  methods: ["GET"]
  defaults: { _controller: App\Controller\PostController::index }

app_post_show:
  path: /post/{id}
  methods: ["GET"]
  defaults: { _controller: App\Controller\PostController::show }

app_post_delete:
  path: /post/{id}
  methods: ["DELETE"]
  defaults: { _controller: App\Controller\PostController::delete }

